[tool.black]
line-length = 120

[tool.ruff]
line-length = 120
select = ["E", "F", "B", "ISC", "I", "PL", "W605"]
ignore = ["E501", "E731", "F401", "PLR0912", "PLR0913", "PLW2901", "PLW0603"]
# for odoo server actions scripts
builtins = ["env", "model", "record", "records", "time", "datetime", "dateutil", "timezone", "float_compare", "log", "UserError", "Command", "XXXXXX"]
